### ISSUE TITLE
caught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by spiritelf** [xuyd/vue-login#1]
caught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.  atob怎么去掉不行？

**Comment by xuyd** [comment]
这个报错应该是window.atob()里的字符串格式不正确吧

**Comment by spiritelf** [comment]
beforeEach 这个加断点调试不到可能是什么？

**Comment by xuyd** [comment]
那可以不加断点试试
